# scripts/agent-run.ps1 — agent-driven verification harness driver (Windows)
# Generated by /andromeda-setup-project Phase 4 from test-plan §3 + obs-plan §3.
# Maintenance: re-run /andromeda-setup-project after either plan changes.
#
# Mirrors agent-run.sh — same 5 commands, same semantics. Conductor has NO daemon and NO
# inbound listener: boot is a preflight gate, status reads disk artifacts, there is no PID file.
#   boot, run, status, cleanup, logs
# Run with: .\scripts\agent-run.ps1 boot

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$Cargo = if ($env:CARGO) { $env:CARGO } else { 'cargo' }
$RunsDir = if ($env:CONDUCTOR_RUNS_DIR) { $env:CONDUCTOR_RUNS_DIR } else { 'runs' }
$RunId = if ($args.Count -ge 2) { $args[1] } else { '' }

switch ($args[0]) {
    'boot' {
        # MCP preflight readiness gate. ready:true => exit 0; ready:false => dependent scenarios
        # report Blocked. CI uses the rmcp stub; the live-Pulse leg needs Pulse's mcp-server feature.
        & $Cargo run -q -p conductor-cli --bin conductor -- preflight --json
    }
    'run' {
        # CI build+test gate (test-plan §9). Optional scenario leg via $env:SCENARIO / $env:SEED.
        & $Cargo nextest run --workspace --profile ci
        & $Cargo test --workspace --doc
        & $Cargo clippy --workspace --all-targets -- -D warnings
        if ($env:SCENARIO) {
            $seed = if ($env:SEED) { $env:SEED } else { '424242' }
            & $Cargo run -q -p conductor-cli --bin conductor -- run $env:SCENARIO --seed $seed
        }
    }
    'status' {
        # Read the Run-report envelope from disk — there is no listener to poll.
        if (-not $RunId) { Write-Error 'usage: .\agent-run.ps1 status <run_id>'; exit 2 }
        $journal = Join-Path $RunsDir "$RunId.jsonl"
        if (-not (Test-Path $journal)) { Write-Error "status: no journal for run_id=$RunId"; exit 1 }
        # Last line carries the final envelope; assert it parses and surface verdict/state.
        $last = Get-Content $journal | Select-Object -Last 1
        $env = $last | ConvertFrom-Json
        $env | Select-Object run_id, seed, scenario, verdict, state, latency_ms, slo_tier | ConvertTo-Json -Compress
    }
    'cleanup' {
        # Idempotent: remove per-run artifacts + the runs.db row + release the :4317 port-occupier.
        # NEVER touch Pulse (no process management).
        if ($RunId) {
            Remove-Item (Join-Path $RunsDir "$RunId.jsonl") -ErrorAction SilentlyContinue
            Remove-Item (Join-Path $RunsDir "$RunId.md") -ErrorAction SilentlyContinue
            $db = Join-Path $RunsDir 'runs.db'
            if ((Test-Path $db) -and (Get-Command sqlite3 -ErrorAction SilentlyContinue)) {
                & sqlite3 $db "DELETE FROM runs WHERE run_id = '$RunId';" 2>$null
            }
        }
        Write-Output ("cleanup: done" + $(if ($RunId) { " ($RunId)" } else { '' }))
    }
    'logs' {
        # The emission journal is ground truth — print it (JSONL, one envelope per line).
        if (-not $RunId) { Write-Error 'usage: .\agent-run.ps1 logs <run_id>'; exit 2 }
        Get-Content (Join-Path $RunsDir "$RunId.jsonl")
    }
    default {
        Write-Error 'Usage: .\agent-run.ps1 {boot|run|status|cleanup|logs} [run_id]'
        exit 2
    }
}
