#!/usr/bin/env bash
# scripts/agent-run.sh — agent-driven verification harness driver
# Generated by /andromeda-setup-project Phase 4 from test-plan §3 + obs-plan §3.
# Maintenance: re-run /andromeda-setup-project after either plan changes.
#
# Conductor has NO daemon and NO inbound listener (test-plan §3) — boot is a preflight
# gate, status reads disk artifacts, there is no PID file:
#   boot     — MCP preflight readiness gate (one-shot; protocol 2024-11-05 + tools + data-dir canary)
#   run      — nextest + doctest + clippy (+ optional scenario via SCENARIO=/SEED=)
#   status   — read the Run-report envelope from runs/<run_id>.jsonl (no HTTP/IPC endpoint)
#   cleanup  — remove run artifacts + runs.db row + release the :4317 port-occupier (idempotent)
#   logs     — print the per-run JSONL emission journal (the left side of every SLO check)
#
# Bound contracts: test-plan §3 (5-command discipline, envelope, no PID file) · obs-plan §3 (JSONL format).

set -euo pipefail

CARGO="${CARGO:-cargo}"
RUNS_DIR="${CONDUCTOR_RUNS_DIR:-runs}"
RUN_ID="${2:-}"
PREFLIGHT_TIMEOUT_SEC="${CONDUCTOR_PREFLIGHT_TIMEOUT:-30}"

case "${1:-}" in
  boot)
    # MCP preflight readiness gate. ready:true => exit 0; ready:false => dependent scenarios
    # report Blocked (never a silent downgrade). CI uses the rmcp stub; the live-Pulse leg needs
    # Pulse's mcp-server feature + ANDROMEDA_PULSE_MCP_ENABLED + matching ANDROMEDA_PULSE_DATA_DIR.
    timeout "${PREFLIGHT_TIMEOUT_SEC}" "$CARGO" run -q -p conductor-cli --bin conductor -- preflight --json
    ;;

  run)
    # CI build+test gate (test-plan §9). Stage flags: --unit | --integration | --e2e (default: all).
    "$CARGO" nextest run --workspace --profile ci
    "$CARGO" test --workspace --doc
    "$CARGO" clippy --workspace --all-targets -- -D warnings
    # Optional scenario leg: SCENARIO=<name|P-ID> SEED=<n> scripts/agent-run.sh run
    if [ -n "${SCENARIO:-}" ]; then
      "$CARGO" run -q -p conductor-cli --bin conductor -- run "$SCENARIO" --seed "${SEED:-424242}"
    fi
    ;;

  status)
    # Read the Run-report envelope from disk — there is no listener to poll.
    [ -n "$RUN_ID" ] || { echo "usage: $0 status <run_id>" >&2; exit 2; }
    journal="$RUNS_DIR/$RUN_ID.jsonl"
    [ -f "$journal" ] || { echo "status: no journal for run_id=$RUN_ID" >&2; exit 1; }
    # Last line carries the final envelope; assert it parses and surface verdict/state.
    tail -n 1 "$journal" | jq -e '{run_id, seed, scenario, verdict, state, latency_ms, slo_tier}'
    ;;

  cleanup)
    # Idempotent: remove per-run artifacts + the runs.db row + release the :4317 port-occupier.
    # NEVER touch Pulse (no process management). run_id is a filesystem-safe hyphen-delimited stamp.
    if [ -n "$RUN_ID" ]; then
      rm -f "$RUNS_DIR/$RUN_ID.jsonl" "$RUNS_DIR/$RUN_ID.md"
      if [ -f "$RUNS_DIR/runs.db" ] && command -v sqlite3 >/dev/null 2>&1; then
        sqlite3 "$RUNS_DIR/runs.db" "DELETE FROM runs WHERE run_id = '$RUN_ID';" 2>/dev/null || true
      fi
    fi
    echo "cleanup: done${RUN_ID:+ ($RUN_ID)}"
    ;;

  logs)
    # The emission journal is ground truth — print it (JSONL, one envelope per line).
    [ -n "$RUN_ID" ] || { echo "usage: $0 logs <run_id>" >&2; exit 2; }
    cat "$RUNS_DIR/$RUN_ID.jsonl"
    ;;

  *)
    echo "Usage: $0 {boot|run|status|cleanup|logs} [run_id]" >&2
    exit 2
    ;;
esac
