# scripts/agent-run.ps1 — agent-driven verification harness driver (Windows)
# Generated by /andromeda-setup-project Phase 4 from test-plan §3 + obs-plan §3.
# Maintenance: re-run /andromeda-setup-project after either plan changes.
#
# Mirrors agent-run.sh — same 5 commands, same semantics. Conductor has NO daemon and NO inbound
# listener: boot is a preflight gate, status reads disk artifacts, there is no PID file.
#   boot, run [--unit|--integration|--e2e|--live], status [run_id], cleanup [run_id], logs [run_id]
#   --live is the operator-gated live-Pulse suite: never a CI gate, never reachable from a bare `run`
# Run with: .\scripts\agent-run.ps1 boot

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$Cargo = if ($env:CARGO) { $env:CARGO } else { 'cargo' }
$RunsDir = if ($env:CONDUCTOR_RUNS_DIR) { $env:CONDUCTOR_RUNS_DIR } else { 'runs' }
$UiDir = 'crates/conductor-tauri/ui'
$Arg1 = if ($args.Count -ge 2) { $args[1] } else { '' }
$RunContract = 'contracts/pulse-run-contract.toml'

# Read a bare `key = <integer>` term from the pinned run contract. A missing term is fatal, never
# defaulted: a silently-defaulted budget is how the wrapper came to be shorter than the run it guards.
function Get-RunContractTerm([string]$Key) {
    foreach ($line in Get-Content -Path $RunContract) {
        if ($line -match "^\s*$Key\s*=\s*(\d+)") { return [int]$Matches[1] }
    }
    [Console]::Error.WriteLine("boot: $Key not found in $RunContract")
    exit 2
}

# The `boot` wall-clock budget. CONDUCTOR_PREFLIGHT_TIMEOUT is the in-process canary POLL budget, which
# the contract's floor raises; the warm-up pre-roll runs BEFORE that poll starts, so a wrapper set to the
# poll alone kills the run mid-poll. Budget = warm-up + poll + margin (test-plan §3, contract
# [incident_formation]).
function Get-PreflightBudgetSec {
    $warmupMs = Get-RunContractTerm 'warmup_ms'
    $pollFloor = Get-RunContractTerm 'min_canary_poll_seconds'
    $poll = if ($env:CONDUCTOR_PREFLIGHT_TIMEOUT) { [int]$env:CONDUCTOR_PREFLIGHT_TIMEOUT } else { $pollFloor }
    if ($poll -lt $pollFloor) { $poll = $pollFloor }
    [int]([math]::Floor($warmupMs / 1000) + $poll + 30)
}

# conductor-tauri's generate_context! resolves build.frontendDist (ui/dist) at COMPILE time, so the
# webview bundle must exist before any workspace cargo build/nextest/clippy compiles conductor-tauri.
function Invoke-EnsureFrontend {
    Push-Location $UiDir
    try {
        if (-not (Test-Path 'node_modules')) {
            & npm ci
            if ($LASTEXITCODE -ne 0) { throw "npm ci failed ($LASTEXITCODE)" }
        }
        & npm run build
        if ($LASTEXITCODE -ne 0) { throw "npm run build failed ($LASTEXITCODE)" }
    } finally { Pop-Location }
}

# A run_id is a filesystem-safe hyphen-delimited stamp; reject anything else before it reaches a path
# join or a sqlite3 statement (security-plan §Input Validation — no string-concat SQL on raw input).
function Test-RunId([string]$Id) { $Id -match '^[0-9A-Za-z._-]+$' }

# The newest run's id — the lexicographically greatest <run_id>.jsonl stem (run_ids sort by time).
function Get-LatestRunId {
    $newest = ''
    foreach ($f in Get-ChildItem -Path $RunsDir -Filter '*.jsonl' -ErrorAction SilentlyContinue) {
        if ($f.BaseName -gt $newest) { $newest = $f.BaseName }
    }
    $newest
}

# Resolve the run_id arg, defaulting to the latest run; validate it (exits on miss / reject).
function Resolve-RunId([string]$Id, [string]$Verb) {
    if (-not $Id) { $Id = Get-LatestRunId }
    if (-not $Id) { [Console]::Error.WriteLine("${Verb}: no run found in $RunsDir"); exit 1 }
    if (-not (Test-RunId $Id)) { [Console]::Error.WriteLine("${Verb}: invalid run_id"); exit 2 }
    $Id
}

# --- the operator-gated live suite (`run --live`) ------------------------------------------------
# The self-obs sink is TRUNCATING (conductor-core obs.rs) — every --agent-mode invocation wipes the
# previous leg's lines — so each leg's stream is frozen before the next one runs. A per-leg
# CONDUCTOR_RUNS_DIR would NOT separate them: the path resolves as runs_dir.parent()/logs, so every
# runs dir under runs/ lands in the same logs dir.
$LiveLog = Join-Path (Split-Path -Parent (Join-Path (Get-Location) $RunsDir)) 'logs/agent-latest.jsonl'
$LiveCaptureDir = Join-Path $RunsDir 'live-suite'

# Total wall clock ~12-15 min. Each preflight pays the contract's warm-up before its poll starts, and a
# NOT-ready gate pays the whole poll floor. Per-leg budget = preflight budget + the scenario's phases + margin.
function Get-LiveLegBudgetSec([int]$ScenarioSec) { (Get-PreflightBudgetSec) + $ScenarioSec + 60 }

# Drive one scenario leg and freeze its self-obs. A Blocked row is a REPORTED state and exits 0 (only a
# hard Fail exits non-zero), which is what lets B2's deduped gate be an expected outcome, not an abort.
function Invoke-LiveLeg([string]$Label, [string]$Scenario, [int]$Budget) {
    Write-Output "[live] leg ${Label}: $Scenario"
    $p = Start-Process -FilePath $Cargo -NoNewWindow -PassThru -ArgumentList @(
        'run', '-q', '-p', 'conductor-cli', '--bin', 'conductor', '--', 'run', $Scenario, '--agent-mode')
    if (-not $p.WaitForExit($Budget * 1000)) {
        [Console]::Error.WriteLine("[live] leg ${Label}: exceeded the ${Budget}s budget - terminating")
        $p.Kill(); $p.WaitForExit()
        exit 124
    }
    if ($p.ExitCode -ne 0) { throw "[live] leg ${Label} exited $($p.ExitCode)" }
    New-Item -ItemType Directory -Force -Path $LiveCaptureDir | Out-Null
    if (Test-Path $LiveLog) {
        Copy-Item $LiveLog (Join-Path $LiveCaptureDir "$Label.jsonl") -Force
        $n = (Get-Content (Join-Path $LiveCaptureDir "$Label.jsonl")).Count
        Write-Output "[live] leg ${Label}: froze $n self-obs lines"
    } else {
        [Console]::Error.WriteLine("[live] leg ${Label}: no self-obs stream at $LiveLog")
    }
}

function Invoke-LiveSuite {
    # The probe leads and short-circuits: non-mutating, fires NO canary, so it primes none of the
    # incident state the legs depend on. An unmet subject REFUSES the suite rather than letting a
    # partial env degrade to a ~0s [BLOCKED] row.
    & $Cargo run -q -p conductor-cli --bin conductor -- preconditions
    if ($LASTEXITCODE -ne 0) {
        [Console]::Error.WriteLine('run --live: refused - a live-Pulse precondition is unmet (above); no leg was fired')
        exit 1
    }

    # Clear last run's captures so an aborted run's stale leg file is never mis-read as this run's.
    # Non-recursive by design — see the .sh sibling.
    New-Item -ItemType Directory -Force -Path $LiveCaptureDir | Out-Null
    Remove-Item (Join-Path $LiveCaptureDir '*.jsonl') -Force -ErrorAction SilentlyContinue

    # live_leg_order — H runs FIRST; B1 and B2 are the SAME short scenario fired twice on purpose.
    #   H   halo-hue-encoding drives a sustained 2/s identical-fingerprint stream for 150s, so its own
    #       dot is still live when Pulse flips its severity tier and the hue observable fires against a
    #       tick-refreshed last_seen. It runs FIRST because its stream must not sit inside leg A's
    #       silence window; its own incident then idles from phase-2 end and auto-resolves well before
    #       A reads back. NOTE the hue leaf fires from the COMPACT-WIDGET window (ConstellationCanvas
    #       is mounted only there) — a dashboard-only session records no sample.
    #   B1  gate ready; read-back finds its own canary incident still open -> a graded manual row.
    #   B2  fired immediately, inside Pulse's 120s idle window: its canary dedupes against B1's
    #       still-open incident on the (kind, scope, scope_id) tuple, no fresh incident forms, and the
    #       gate goes not-ready-but-CONNECTED — the only state reaching the readiness-gate self-obs line.
    #       ANDROMEDA_PULSE_L4_DETERMINISTIC is load-bearing: canned-L4 formation is ~2s, so B2's storm
    #       lands well inside the window; real-model formation (~110s) would fall outside it.
    #   A   after the quiet window, a fresh canary forms then idles for the whole silent scenario, so
    #       read-back finds an EMPTY active set — the auto-resolve residual arm.
    Invoke-LiveLeg 'h' 'halo-hue-encoding' (Get-LiveLegBudgetSec 180)

    Invoke-LiveLeg 'b1' 'degraded-mode-report' (Get-LiveLegBudgetSec 10)
    Invoke-LiveLeg 'b2' 'degraded-mode-report' (Get-LiveLegBudgetSec 10)

    Write-Output '[live] quiet window: 150s (Pulse 120s idle + a 30s resolver tick) before leg a'
    Start-Sleep -Seconds 150

    Invoke-LiveLeg 'a' 'auto-resolve-idle-window' (Get-LiveLegBudgetSec 180)

    # The driven a11y arm fires its own preflight canary; leg A's canary has already resolved by A's
    # read-back, so no extra window is needed. It self-skips at exit 0 when no native WebDriver resolves
    # (wdio.conf.ts guards CONDUCTOR_MSEDGEDRIVER) — a SKIP, not a refusal: a host-tool handle and a
    # live-Pulse handle are different classes.
    Write-Output '[live] driven a11y arm'
    Invoke-EnsureFrontend
    & $Cargo build --release -p conductor-tauri --features tauri/custom-protocol
    if ($LASTEXITCODE -ne 0) { throw "cargo build --release failed ($LASTEXITCODE)" }
    Push-Location $UiDir
    try {
        & npm run a11y:driven
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    } finally { Pop-Location }

    Write-Output "[live] suite complete - captures under $LiveCaptureDir"
    Write-Output '[live] bootstrap posture: leg A''s empty-active-set arm needs the silence evaluator disarmed.'
    Write-Output '[live] The operator''s pulse-app launch carries ANDROMEDA_PULSE_BASELINE_BOOTSTRAP_SECONDS=86399.'
    Write-Output '[live] It is BOOT-WIDE (Thresholds::from_env runs once at boot), load-bearing for leg A and inert'
    Write-Output '[live] for leg H - the storm path consults no baseline. Conductor never sets it; confirm which'
    Write-Output '[live] posture booted by grepping Pulse''s log for the TARGET triage.baseline.bootstrap_window.override'
    Write-Output '[live] (level WARN, reason="env_override", resolved_seconds) - the emitting fn name is not in the log.'
    Write-Output '[live] stop form: the wdio arm self-terminates via onComplete -> tauriDriver.kill(); after an'
    Write-Output '[live] interrupted run: taskkill /F /IM msedgedriver.exe /IM conductor-tauri.exe (+ the node CLI).'
    Write-Output '[live] pulse-app is NOT stopped here - the operator started it and stops it.'
}

switch ($args[0]) {
    'boot' {
        # ready:true ⇒ exit 0; ready:false ⇒ non-zero (gate). With no live Pulse this is ready:false —
        # so the CI gate dogfoods `run`, not `boot`. The live-Pulse leg needs Pulse's mcp-server feature.
        #
        # The precondition probe runs FIRST and short-circuits, SKIPPING the preflight rather than
        # paying it: an unmet launch condition explains a failed canary, so surfacing the canary
        # symptom first sends the operator to the wrong cause and spends the whole budget doing it.
        # The probe fires no canary, so it primes none of the state the preflight then dedupes
        # against. Identical semantics to agent-run.sh (test-plan §3 binds .sh/.ps1 parity).
        & $Cargo run -q -p conductor-cli --bin conductor -- preconditions
        if ($LASTEXITCODE -ne 0) {
            [Console]::Error.WriteLine("boot: skipped preflight - a live-Pulse precondition is unmet (above)")
            exit 1
        }
        $budget = Get-PreflightBudgetSec
        $p = Start-Process -FilePath $Cargo -NoNewWindow -PassThru -ArgumentList @(
            'run', '-q', '-p', 'conductor-cli', '--bin', 'conductor', '--', 'preflight', '--json')
        if (-not $p.WaitForExit($budget * 1000)) {
            [Console]::Error.WriteLine("boot: preflight exceeded the ${budget}s budget - terminating")
            $p.Kill()
            $p.WaitForExit()
            exit 124
        }
        exit $p.ExitCode
    }
    'run' {
        # Stage flags partition the CI gate (test-plan §9); no flag = the full bundled gate.
        switch ($Arg1) {
            '--unit'        { Invoke-EnsureFrontend; & $Cargo nextest run --workspace --profile ci; break }
            '--integration' { Invoke-EnsureFrontend; & $Cargo nextest run --workspace --profile ci -E 'kind(test)'; break }
            # test-plan §3/§9: --e2e IS the tauri-driver `wdio run` leg. The bundle must be built before
            # the compile (generate_context! resolves frontendDist at compile time), and the binary must
            # embed it rather than loading tauri.conf.json's devUrl. What decides that is the
            # `custom-protocol` FEATURE, not the profile: tauri's build.rs computes `dev = !custom_protocol`
            # and tauri-build reads it back through DEP_TAURI_DEV, so a bare `--release` build still loads
            # localhost:5173 (measured 2026-09-01). The leg skips at exit 0 with no native WebDriver.
            '--e2e' {
                Invoke-EnsureFrontend
                & $Cargo build --release -p conductor-tauri --features tauri/custom-protocol
                if ($LASTEXITCODE -ne 0) { throw "cargo build --release failed ($LASTEXITCODE)" }
                Push-Location $UiDir
                try {
                    & npm run a11y
                    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
                } finally { Pop-Location }
                break
            }
            '' {
                Invoke-EnsureFrontend
                & $Cargo nextest run --workspace --profile ci
                & $Cargo test --workspace --doc
                & $Cargo clippy --workspace --all-targets -- -D warnings
                if ($env:SCENARIO) {
                    # --agent-mode: JSON self-obs to logs/agent-latest.jsonl + never block on an operator pause.
                    # --seed rides ONLY an explicitly set SEED — files-over-env-defaults precedence
                    # (arch §Config management): the TOML-declared seed governs when SEED is unset.
                    if ($env:SEED) {
                        & $Cargo run -q -p conductor-cli --bin conductor -- run $env:SCENARIO --seed $env:SEED --agent-mode
                    } else {
                        & $Cargo run -q -p conductor-cli --bin conductor -- run $env:SCENARIO --agent-mode
                    }
                }
                break
            }
            # test-plan §9: the operator-gated live suite. NEVER a CI gate and never reachable from a
            # bare `run` — a live leg drives a real Pulse. Composes H -> B1 -> B2 -> quiet window -> A ->
            # the driven a11y arm, in that order, because each leg's outcome depends on the incident
            # state the previous one left.
            '--live' { Invoke-LiveSuite; break }
            default { [Console]::Error.WriteLine('usage: .\agent-run.ps1 run [--unit|--integration|--e2e|--live]'); exit 2 }
        }
    }
    'status' {
        # Read the Run-report envelope from disk — there is no listener to poll.
        $id = Resolve-RunId $Arg1 'status'
        $journal = Join-Path $RunsDir "$id.jsonl"
        if (-not (Test-Path $journal)) { [Console]::Error.WriteLine("status: no journal for run_id=$id"); exit 1 }
        # Surface the last ENVELOPE row, not the last line: per-check records ride the same journal
        # (arch §Standard Contracts — Per-check record), and `seed` is envelope-only, so a run that
        # graded checks would otherwise report a CheckRecord's nulls as its envelope.
        $envelope = Get-Content $journal |
            Where-Object { $_.Trim() } |
            ForEach-Object { $_ | ConvertFrom-Json } |
            Where-Object { $_.PSObject.Properties.Name -contains 'seed' } |
            Select-Object -Last 1
        if (-not $envelope) { [Console]::Error.WriteLine("status: no envelope row in the journal for run_id=$id"); exit 1 }
        $envelope | Select-Object run_id, seed, scenario, verdict, state, latency_ms, slo_tier | ConvertTo-Json -Compress
    }
    'cleanup' {
        # Idempotent: remove a run's artifacts + its runs.db row. NEVER touch Pulse (no process mgmt).
        if ($Arg1) {
            if (-not (Test-RunId $Arg1)) { [Console]::Error.WriteLine('cleanup: invalid run_id'); exit 2 }
            Remove-Item (Join-Path $RunsDir "$Arg1.jsonl") -ErrorAction SilentlyContinue
            Remove-Item (Join-Path $RunsDir "$Arg1.md") -ErrorAction SilentlyContinue
            # Teardown goes through the binary: rusqlite BOUND parameters over every table a run
            # writes (runs, run_check, run_envelope), which the sqlite3 CLI can neither bind nor be
            # assumed present — it is on no host here and on no CI runner (test-plan §3 cleanup body).
            $db = Join-Path $RunsDir 'runs.db'
            if (Test-Path $db) {
                & $Cargo run -q -p conductor-cli --bin conductor -- cleanup $Arg1
            }
        }
        Write-Output ("cleanup: done" + $(if ($Arg1) { " ($Arg1)" } else { '' }))
    }
    'logs' {
        # The emission journal is ground truth — print it (JSONL, one envelope per line).
        $id = Resolve-RunId $Arg1 'logs'
        $journal = Join-Path $RunsDir "$id.jsonl"
        if (-not (Test-Path $journal)) { [Console]::Error.WriteLine("logs: no journal for run_id=$id"); exit 1 }
        Get-Content $journal
    }
    default {
        [Console]::Error.WriteLine('Usage: .\agent-run.ps1 {boot|run [--unit|--integration|--e2e]|status [run_id]|cleanup [run_id]|logs [run_id]}')
        exit 2
    }
}
