# scripts/agent-run.ps1 — agent-driven verification harness driver (Windows)
# Generated by /andromeda-setup-project Phase 4 from test-plan §3 + obs-plan §3.
# Maintenance: re-run /andromeda-setup-project after either plan changes.
#
# Mirrors agent-run.sh — same 5 commands, same semantics. Conductor has NO daemon and NO inbound
# listener: boot is a preflight gate, status reads disk artifacts, there is no PID file.
#   boot, run [--unit|--integration|--e2e], status [run_id], cleanup [run_id], logs [run_id]
# Run with: .\scripts\agent-run.ps1 boot

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$Cargo = if ($env:CARGO) { $env:CARGO } else { 'cargo' }
$RunsDir = if ($env:CONDUCTOR_RUNS_DIR) { $env:CONDUCTOR_RUNS_DIR } else { 'runs' }
$UiDir = 'crates/conductor-tauri/ui'
$Arg1 = if ($args.Count -ge 2) { $args[1] } else { '' }
$RunContract = 'contracts/pulse-run-contract.toml'

# Read a bare `key = <integer>` term from the pinned run contract. A missing term is fatal, never
# defaulted: a silently-defaulted budget is how the wrapper came to be shorter than the run it guards.
function Get-RunContractTerm([string]$Key) {
    foreach ($line in Get-Content -Path $RunContract) {
        if ($line -match "^\s*$Key\s*=\s*(\d+)") { return [int]$Matches[1] }
    }
    [Console]::Error.WriteLine("boot: $Key not found in $RunContract")
    exit 2
}

# The `boot` wall-clock budget. CONDUCTOR_PREFLIGHT_TIMEOUT is the in-process canary POLL budget, which
# the contract's floor raises; the warm-up pre-roll runs BEFORE that poll starts, so a wrapper set to the
# poll alone kills the run mid-poll. Budget = warm-up + poll + margin (test-plan §3, contract
# [incident_formation]).
function Get-PreflightBudgetSec {
    $warmupMs = Get-RunContractTerm 'warmup_ms'
    $pollFloor = Get-RunContractTerm 'min_canary_poll_seconds'
    $poll = if ($env:CONDUCTOR_PREFLIGHT_TIMEOUT) { [int]$env:CONDUCTOR_PREFLIGHT_TIMEOUT } else { $pollFloor }
    if ($poll -lt $pollFloor) { $poll = $pollFloor }
    [int]([math]::Floor($warmupMs / 1000) + $poll + 30)
}

# conductor-tauri's generate_context! resolves build.frontendDist (ui/dist) at COMPILE time, so the
# webview bundle must exist before any workspace cargo build/nextest/clippy compiles conductor-tauri.
function Invoke-EnsureFrontend {
    Push-Location $UiDir
    try {
        if (-not (Test-Path 'node_modules')) {
            & npm ci
            if ($LASTEXITCODE -ne 0) { throw "npm ci failed ($LASTEXITCODE)" }
        }
        & npm run build
        if ($LASTEXITCODE -ne 0) { throw "npm run build failed ($LASTEXITCODE)" }
    } finally { Pop-Location }
}

# A run_id is a filesystem-safe hyphen-delimited stamp; reject anything else before it reaches a path
# join or a sqlite3 statement (security-plan §Input Validation — no string-concat SQL on raw input).
function Test-RunId([string]$Id) { $Id -match '^[0-9A-Za-z._-]+$' }

# The newest run's id — the lexicographically greatest <run_id>.jsonl stem (run_ids sort by time).
function Get-LatestRunId {
    $newest = ''
    foreach ($f in Get-ChildItem -Path $RunsDir -Filter '*.jsonl' -ErrorAction SilentlyContinue) {
        if ($f.BaseName -gt $newest) { $newest = $f.BaseName }
    }
    $newest
}

# Resolve the run_id arg, defaulting to the latest run; validate it (exits on miss / reject).
function Resolve-RunId([string]$Id, [string]$Verb) {
    if (-not $Id) { $Id = Get-LatestRunId }
    if (-not $Id) { [Console]::Error.WriteLine("${Verb}: no run found in $RunsDir"); exit 1 }
    if (-not (Test-RunId $Id)) { [Console]::Error.WriteLine("${Verb}: invalid run_id"); exit 2 }
    $Id
}

switch ($args[0]) {
    'boot' {
        # ready:true ⇒ exit 0; ready:false ⇒ non-zero (gate). With no live Pulse this is ready:false —
        # so the CI gate dogfoods `run`, not `boot`. The live-Pulse leg needs Pulse's mcp-server feature.
        $budget = Get-PreflightBudgetSec
        $p = Start-Process -FilePath $Cargo -NoNewWindow -PassThru -ArgumentList @(
            'run', '-q', '-p', 'conductor-cli', '--bin', 'conductor', '--', 'preflight', '--json')
        if (-not $p.WaitForExit($budget * 1000)) {
            [Console]::Error.WriteLine("boot: preflight exceeded the ${budget}s budget - terminating")
            $p.Kill()
            $p.WaitForExit()
            exit 124
        }
        exit $p.ExitCode
    }
    'run' {
        # Stage flags partition the CI gate (test-plan §9); no flag = the full bundled gate.
        switch ($Arg1) {
            '--unit'        { Invoke-EnsureFrontend; & $Cargo nextest run --workspace --profile ci; break }
            '--integration' { Invoke-EnsureFrontend; & $Cargo nextest run --workspace --profile ci -E 'kind(test)'; break }
            # test-plan §3/§9: --e2e IS the tauri-driver `wdio run` leg. The bundle must be built before
            # the compile (generate_context! resolves frontendDist at compile time), and the binary must
            # embed it rather than loading tauri.conf.json's devUrl. What decides that is the
            # `custom-protocol` FEATURE, not the profile: tauri's build.rs computes `dev = !custom_protocol`
            # and tauri-build reads it back through DEP_TAURI_DEV, so a bare `--release` build still loads
            # localhost:5173 (measured 2026-09-01). The leg skips at exit 0 with no native WebDriver.
            '--e2e' {
                Invoke-EnsureFrontend
                & $Cargo build --release -p conductor-tauri --features tauri/custom-protocol
                if ($LASTEXITCODE -ne 0) { throw "cargo build --release failed ($LASTEXITCODE)" }
                Push-Location $UiDir
                try {
                    & npm run a11y
                    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
                } finally { Pop-Location }
                break
            }
            '' {
                Invoke-EnsureFrontend
                & $Cargo nextest run --workspace --profile ci
                & $Cargo test --workspace --doc
                & $Cargo clippy --workspace --all-targets -- -D warnings
                if ($env:SCENARIO) {
                    # --agent-mode: JSON self-obs to logs/agent-latest.jsonl + never block on an operator pause.
                    # --seed rides ONLY an explicitly set SEED — files-over-env-defaults precedence
                    # (arch §Config management): the TOML-declared seed governs when SEED is unset.
                    if ($env:SEED) {
                        & $Cargo run -q -p conductor-cli --bin conductor -- run $env:SCENARIO --seed $env:SEED --agent-mode
                    } else {
                        & $Cargo run -q -p conductor-cli --bin conductor -- run $env:SCENARIO --agent-mode
                    }
                }
                break
            }
            default { [Console]::Error.WriteLine('usage: .\agent-run.ps1 run [--unit|--integration|--e2e]'); exit 2 }
        }
    }
    'status' {
        # Read the Run-report envelope from disk — there is no listener to poll.
        $id = Resolve-RunId $Arg1 'status'
        $journal = Join-Path $RunsDir "$id.jsonl"
        if (-not (Test-Path $journal)) { [Console]::Error.WriteLine("status: no journal for run_id=$id"); exit 1 }
        # Last line carries the final envelope; assert it parses and surface verdict/state.
        $last = Get-Content $journal | Select-Object -Last 1
        $envelope = $last | ConvertFrom-Json
        $envelope | Select-Object run_id, seed, scenario, verdict, state, latency_ms, slo_tier | ConvertTo-Json -Compress
    }
    'cleanup' {
        # Idempotent: remove a run's artifacts + its runs.db row. NEVER touch Pulse (no process mgmt).
        if ($Arg1) {
            if (-not (Test-RunId $Arg1)) { [Console]::Error.WriteLine('cleanup: invalid run_id'); exit 2 }
            Remove-Item (Join-Path $RunsDir "$Arg1.jsonl") -ErrorAction SilentlyContinue
            Remove-Item (Join-Path $RunsDir "$Arg1.md") -ErrorAction SilentlyContinue
            $db = Join-Path $RunsDir 'runs.db'
            if ((Test-Path $db) -and (Get-Command sqlite3 -ErrorAction SilentlyContinue)) {
                & sqlite3 $db "DELETE FROM runs WHERE run_id = '$Arg1';" 2>$null
            }
        }
        Write-Output ("cleanup: done" + $(if ($Arg1) { " ($Arg1)" } else { '' }))
    }
    'logs' {
        # The emission journal is ground truth — print it (JSONL, one envelope per line).
        $id = Resolve-RunId $Arg1 'logs'
        $journal = Join-Path $RunsDir "$id.jsonl"
        if (-not (Test-Path $journal)) { [Console]::Error.WriteLine("logs: no journal for run_id=$id"); exit 1 }
        Get-Content $journal
    }
    default {
        [Console]::Error.WriteLine('Usage: .\agent-run.ps1 {boot|run [--unit|--integration|--e2e]|status [run_id]|cleanup [run_id]|logs [run_id]}')
        exit 2
    }
}
