#!/usr/bin/env bash
# scripts/agent-run.sh — agent-driven verification harness driver
# Generated by /andromeda-setup-project Phase 4 from test-plan §3 + obs-plan §3.
# Maintenance: re-run /andromeda-setup-project after either plan changes.
#
# Conductor has NO daemon and NO inbound listener (test-plan §3) — boot is a preflight gate,
# status reads disk artifacts, there is no PID file:
#   boot     — MCP preflight readiness gate (conductor preflight --json; ready:true ⇒ exit 0,
#              ready:false ⇒ non-zero gate + dependent scenarios report Blocked)
#   run      — nextest + doctest + clippy (+ optional SCENARIO=/SEED= leg); stage flags
#              --unit | --integration | --e2e (default: the full bundled gate), test-plan §9
#   status   — read the Run-report envelope from runs/<run_id>.jsonl (latest run if id omitted)
#   cleanup  — remove a run's artifacts + its runs.db row (idempotent); NEVER touches Pulse
#   logs     — print the per-run JSONL emission journal (latest run if id omitted)
#
# Bound contracts: test-plan §3 (5-command discipline, envelope, no PID file) · obs-plan §3 (JSONL format).

set -euo pipefail

CARGO="${CARGO:-cargo}"
RUNS_DIR="${CONDUCTOR_RUNS_DIR:-runs}"
UI_DIR="crates/conductor-tauri/ui"
PREFLIGHT_TIMEOUT_SEC="${CONDUCTOR_PREFLIGHT_TIMEOUT:-30}"

# conductor-tauri's generate_context! resolves build.frontendDist (ui/dist) at COMPILE time, so the
# webview bundle must exist before any workspace cargo build/nextest/clippy compiles conductor-tauri
# (Epoch 9 frameless-window-shell). Install deps only when missing; always rebuild the bundle.
ensure_frontend() {
  ( cd "$UI_DIR" && { [ -d node_modules ] || npm ci; } && npm run build )
}

# A run_id is a filesystem-safe hyphen-delimited stamp; reject anything else before it reaches a path
# join or a sqlite3 statement (security-plan §Input Validation — no string-concat SQL on raw input).
valid_run_id() { [[ "$1" =~ ^[0-9A-Za-z._-]+$ ]]; }

# The newest run's id — the lexicographically greatest <run_id>.jsonl stem (run_ids sort by time).
latest_run_id() {
  local f stem newest=""
  for f in "$RUNS_DIR"/*.jsonl; do
    [ -e "$f" ] || continue
    stem="$(basename "$f" .jsonl)"
    if [[ "$stem" > "$newest" ]]; then newest="$stem"; fi
  done
  printf '%s' "$newest"
}

case "${1:-}" in
  boot)
    # ready:true ⇒ exit 0; ready:false ⇒ non-zero (gate) + dependent scenarios Blocked (never a silent
    # downgrade). With no live Pulse this is ready:false — so the CI gate dogfoods `run`, not `boot`;
    # the live-Pulse leg needs Pulse's mcp-server feature + ANDROMEDA_PULSE_MCP_ENABLED + a matching
    # ANDROMEDA_PULSE_DATA_DIR.
    timeout "${PREFLIGHT_TIMEOUT_SEC}" "$CARGO" run -q -p conductor-cli --bin conductor -- preflight --json
    ;;

  run)
    # Stage flags partition the CI gate (test-plan §9); no flag = the full bundled gate.
    case "${2:-}" in
      --unit)        ensure_frontend; "$CARGO" nextest run --workspace --profile ci ;;
      --integration) ensure_frontend; "$CARGO" nextest run --workspace --profile ci -E 'kind(test)' ;;
      --e2e)         "$CARGO" nextest run -p conductor-cli --profile ci ;;
      "")
        ensure_frontend
        "$CARGO" nextest run --workspace --profile ci
        "$CARGO" test --workspace --doc
        "$CARGO" clippy --workspace --all-targets -- -D warnings
        # Optional scenario leg: SCENARIO=<name|P-ID> SEED=<n> scripts/agent-run.sh run
        # --agent-mode: JSON self-obs to logs/agent-latest.jsonl + never block on an operator pause.
        if [ -n "${SCENARIO:-}" ]; then
          "$CARGO" run -q -p conductor-cli --bin conductor -- run "$SCENARIO" --seed "${SEED:-424242}" --agent-mode
        fi
        ;;
      *) echo "usage: $0 run [--unit|--integration|--e2e]" >&2; exit 2 ;;
    esac
    ;;

  status)
    # Read the Run-report envelope from disk — there is no listener to poll.
    id="${2:-}"
    [ -n "$id" ] || id="$(latest_run_id)"
    [ -n "$id" ] || { echo "status: no run found in $RUNS_DIR" >&2; exit 1; }
    valid_run_id "$id" || { echo "status: invalid run_id" >&2; exit 2; }
    journal="$RUNS_DIR/$id.jsonl"
    [ -f "$journal" ] || { echo "status: no journal for run_id=$id" >&2; exit 1; }
    # Last line carries the final envelope; assert it parses and surface verdict/state.
    tail -n 1 "$journal" | jq -e '{run_id, seed, scenario, verdict, state, latency_ms, slo_tier}'
    ;;

  cleanup)
    # Idempotent: remove a run's artifacts + its runs.db row. NEVER touch Pulse (no process management);
    # the :4317 port-occupier is RAII-released when the conductor process exits.
    id="${2:-}"
    if [ -n "$id" ]; then
      valid_run_id "$id" || { echo "cleanup: invalid run_id" >&2; exit 2; }
      rm -f "$RUNS_DIR/$id.jsonl" "$RUNS_DIR/$id.md"
      if [ -f "$RUNS_DIR/runs.db" ] && command -v sqlite3 >/dev/null 2>&1; then
        sqlite3 "$RUNS_DIR/runs.db" "DELETE FROM runs WHERE run_id = '$id';" 2>/dev/null || true
      fi
    fi
    echo "cleanup: done${id:+ ($id)}"
    ;;

  logs)
    # The emission journal is ground truth — print it (JSONL, one envelope per line).
    id="${2:-}"
    [ -n "$id" ] || id="$(latest_run_id)"
    [ -n "$id" ] || { echo "logs: no run found in $RUNS_DIR" >&2; exit 1; }
    valid_run_id "$id" || { echo "logs: invalid run_id" >&2; exit 2; }
    [ -f "$RUNS_DIR/$id.jsonl" ] || { echo "logs: no journal for run_id=$id" >&2; exit 1; }
    cat "$RUNS_DIR/$id.jsonl"
    ;;

  *)
    echo "Usage: $0 {boot|run [--unit|--integration|--e2e]|status [run_id]|cleanup [run_id]|logs [run_id]}" >&2
    exit 2
    ;;
esac
